### ISSUE TITLE
イベント詳細の募集期間の表示バグ

### ISSUE THREAD

**Issue by yonyon-web** [oic-dotconnect/oic-dotconnect#141]

**Comment by ymgn** [comment]
管理画面での開催前・開催中・終了・問題なし　になることを確認
詳細ページでの募集時間中は参加ボタン、募集前や募集終了後は募集期間外になるのを確認
イベント検索画面の表示では、vue側で実装しているのでEventServiceは使用されていないため適用されていないが、Landingと管理では切り替わっているのが確認できる

以上のことから問題なし
